"""Add LLM monitoring stats

Revision ID: 88bbfe046963
Revises: add_chat_session_metadata
Create Date: 2026-02-19 01:03:45.785937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88bbfe046963'
down_revision = 'add_chat_session_metadata'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_chat_messages_session'), table_name='chat_messages')
    op.add_column('chat_sessions', sa.Column('total_llm_calls', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('chat_sessions', sa.Column('total_input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('chat_sessions', sa.Column('total_output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_index(op.f('ix_chat_sessions_domain'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user'), table_name='chat_sessions')
    op.drop_index(op.f('uq_user_domain_active_session'), table_name='chat_sessions', postgresql_where="(status = 'active'::session_status)")
    op.create_index('uq_user_domain_active_session', 'chat_sessions', ['user_id', 'domain_config_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.drop_column('chat_sessions', 'conversation_state')
    op.drop_index(op.f('ix_domain_configs_json'), table_name='domain_configs', postgresql_using='gin')
    op.drop_index(op.f('ix_domain_configs_owner'), table_name='domain_configs')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_domain_configs_owner'), 'domain_configs', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_domain_configs_json'), 'domain_configs', ['config_json'], unique=False, postgresql_using='gin')
    op.add_column('chat_sessions', sa.Column('conversation_state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('uq_user_domain_active_session', table_name='chat_sessions', postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('uq_user_domain_active_session'), 'chat_sessions', ['user_id', 'domain_config_id', 'status'], unique=True, postgresql_where="(status = 'active'::session_status)")
    op.create_index(op.f('ix_chat_sessions_user'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_domain'), 'chat_sessions', ['domain_config_id'], unique=False)
    op.drop_column('chat_sessions', 'total_output_tokens')
    op.drop_column('chat_sessions', 'total_input_tokens')
    op.drop_column('chat_sessions', 'total_llm_calls')
    op.create_index(op.f('ix_chat_messages_session'), 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.drop_table('llm_usage_stats')
    # ### end Alembic commands ###
